targets:
  $default:
    sources:
      exclude:
        - lib/core/proto/generated/**
        - lib/core/database/models/*.g.dart
    builders:
      # Drift 代码生成
      drift_dev:
        enabled: true